# .github/workflows/get_bangumi_info.yml
name: Get Bangumi Info

on:
  schedule:
    - cron: "5 16 * * *"  # UTC 16:05 -> Beijing 00:05
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DatabaseConnectSetting: ${{ secrets.DATABASE_CONNECT_SETTING }}
      DatabaseHost: ${{ secrets.DATABASE_HOST }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore & Build
        run: dotnet build GetBangumiInfo/GetBangumiInfo.csproj --configuration Release

      - name: Run Bangumi Info Update
        run: dotnet run --project GetBangumiInfo/GetBangumiInfo.csproj --configuration Release
